# Generated by Django 5.2.1 on 2025-05-11 19:55

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='update_at')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='capacity')),
                ('price', models.DecimalField(decimal_places=2, help_text='price per seat', max_digits=9, verbose_name='price')),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'tables',
            },
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='update_at')),
                ('date', models.DateField(verbose_name='date')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('number_of_people', models.PositiveSmallIntegerField(verbose_name='number_of_people')),
                ('number_of_seats', models.PositiveSmallIntegerField(verbose_name='number_of_seats')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('booked', 'booked'), ('canceled', 'canceled')], default='pending', verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='restaurant.table', verbose_name='table')),
            ],
            options={
                'verbose_name': 'reserve',
                'verbose_name_plural': 'reserves',
            },
        ),
    ]
